language: python
sudo: false
notifications:
  email: change

python:
  - 3.5
  - 3.6

env:
  global:
    - OPENBLAS_NUM_THREADS=1
    - MKL_NUM_THREADS=1
  matrix:
    - LINTING=1
    - DOCTEST=1
    - COVERAGE=0

matrix:
  include:
  - python: 3.6
    env:
      - COVERAGE=1
  - python: 3.7
    dist: xenial
    sudo: required
  - python: 3.7
    dist: xenial
    sudo: required
    env:
      - DOCTEST=1
  - python: 3.7
    dist: xenial
    sudo: required
    env:
      - COVERAGE=0

before_install:
  - python -m pip install --upgrade pip
  - if [ "${LINTING}" == "1" ]; then
        pip install flake8;
    fi
  - if [ "${COVERAGE}" == "1" ]; then
        pip install coverage coveralls codecov;
    fi

install:
  - if [ "${DOCTEST}" == "1" ]; then
        pip install -e .[doc];
    else
        pip install -e .[tests];
    fi

script:
  - |
    if [ "${LINTING}" == "1" ]; then
        flake8 pyls;
    elif [ "${DOCTEST}" == "1" ]; then
        cd docs;
        make html;
        make doctest;
    else
        if [ "${COVERAGE}" == "1" ]; then
            TEST_ARGS="--cov-report term-missing --cov=pyls";
        fi
        py.test ${TEST_ARGS} pyls;
    fi

after_success:
  - if [ "${COVERAGE}" == "1" ]; then
        coveralls; codecov;
    fi
